local rtt = require('rtt')
assert(rtt.InputPort.read == nil, 'manual input transfer must not be exposed')
assert(rtt.OutputPort.write == nil, 'manual output transfer must not be exposed')
local source = rtt.OutputPort.new('Int32', 'source')
local sink = rtt.InputPort.new('Int32', 'sink')
assert(source:connect(sink))
source:data(37)
assert(source:data() == 37)
assert(sink:data() == 0, 'editing an output image must not publish')
assert(sink:status() == 'NoData')
assert(source:snapshot() == 0, 'uncommitted image must not be visible to observers')
sink:delete()
source:delete()
print('cyclic port image test passed')
